language: node_js
node_js: '8'
cache:
  yarn: true
  directories:
    - node_modules
    - 'interface/.meteor'

sudo: required

addons:
  artifacts:
    paths:
      - $(git ls-files -o | grep -E "^dist_(mist|wallet)/release" | tr "\n" ":")
        
matrix:
  include:
    # LINUX
    - os: linux
      dist: trusty
      env:
          - GULP_PLATFORM=linux
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
            - xz-utils
            - gcc-multilib
            - g++-multilib

    # MAC
    - os: osx
      osx_image: xcode8.3  # currently xcode8.1+ doesn't support electron-builder macOS code-signing (https://github.com/electron-userland/electron-builder/issues/820#issuecomment-267777060)
      env:
          - GULP_PLATFORM=mac
      before_install:
          - npm install -g yarn  # macOS xcode8 image doesn't natively support yarn yet

  fast_finish: true


install:
  - PATH=$PATH:$HOME/.meteor && curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/1390e0f96162d0d70fc1e60a6b0f4f891a0e8f42/configure.sh | /bin/sh

  - yarn

  # prepare integration tests
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3

  # disable macOS code-signing (production certificate) on develop branch
  - if [[ $TRAVIS_BRANCH != "master" ]]; then unset CSC_LINK CSC_KEY_PASSWORD; fi

script:
  - yarn test:unit:once
    
  - yarn gulp --mist --$GULP_PLATFORM

  - yarn gulp --wallet --$GULP_PLATFORM
  
  - yarn gulp test

after_success:
  -|
    if [[ $TRAVIS_BRANCH == "master" ]]; then
      gulp upload-queue --$GULP_PLATFORM;
      gulp upload-queue --wallet --$GULP_PLATFORM;
    fi

